branches:
  only:
  - master
  - travis

language: objective-c
os: osx
osx_image: xcode9.1
env:
  - scheme='Siesta macOS' platform='OS X'
  - scheme='Siesta iOS'   platform='iOS Simulator' ios_version='11.1'   ios_device='iPhone X'
  - scheme='Siesta iOS'   platform='iOS Simulator' ios_version='10.3.1' ios_device='iPhone SE'
  - scheme='Siesta iOS'   platform='iOS Simulator' ios_version='9.3'    ios_device='iPhone 6'
  - scheme='Siesta iOS'   platform='iOS Simulator' ios_version='8.1'    ios_device='iPhone 4s'

before_install: |
  if [[ "$platform" == "iOS Simulator" ]]; then
    ios_simulator_udid=$(
      xcrun simctl create "Siesta testing device" \
          "com.apple.CoreSimulator.SimDeviceType.${ios_device// /-}" \
          "com.apple.CoreSimulator.SimRuntime.iOS-${ios_version//./-}"
    )
    echo "Prelaunching iOS simulator with UDID $ios_simulator_udid"
    open -a "simulator" --args -CurrentDeviceUDID $ios_simulator_udid
  fi

script: |
  # ------ Certificates ------

  # Thanks to https://github.com/Carthage/Carthage/blob/12fb7881876b4987584e49d00befcd2a8b6b354d/script/cibuild#L29-L51
  # but no thanks to Carthage for refusing to do simulator-only builds that would make all these keychain shenanigans unnecessary.

  KEYCHAIN=ios-build.keychain
  local password=cibuild

  # Create a temporary keychain for code signing.

  security create-keychain -p "$password" "$KEYCHAIN"
  security default-keychain -s "$KEYCHAIN"
  security unlock-keychain -p "$password" "$KEYCHAIN"
  security set-keychain-settings -t 3600 -l "$KEYCHAIN"

  # Download the certificate for the Apple cert authority
  local certpath="/tmp/apple_wwdr.cer"
  curl 'https://developer.apple.com/certificationauthority/AppleWWDRCA.cer' > "$certpath"
  security import "$certpath" -k "$KEYCHAIN" -T /usr/bin/codesign

  # Import our development certificate.
  security import ".ios-dev-cert.p12" -k "$KEYCHAIN" -P "$KEY_PASSWORD" -T /usr/bin/codesign
  echo "Available identities after import:"
  security find-identity

  # ------ Tools ------

  set -x

  git clone https://github.com/supermarin/xcpretty.git /tmp/xcpretty

  #brew update
  #brew install carthage

  # ------ Dependencies ------

  # Optional pre-download, because builds are so slow on Travis, and Carthage builds _everything_:
  echo "Downloading prebuilt dependencies"
  curl https://innig.net/tmp/siesta-deps-swift-4.tar.bz2 | bzcat | tar xv

  # Uncomment to build with Carthage instead:
  #echo "Building dependencies"
  #carthage bootstrap --platform iOS,osx #--verbose

  # ------ Project build (at last!) ------

  if [[ "$platform" == "iOS Simulator" ]]; then
    platform="$platform,OS=$ios_version,name=$ios_device"
  fi

  echo
  echo —————— Running tests for $platform ...
  echo

  Siesta_DelayAfterEachSpec=1 \
  Siesta_TestMultipleNetworkProviders=1 \
  travis_retry xcodebuild test \
      -project Siesta.xcodeproj \
      -scheme "$scheme" \
      -destination "platform=$platform" \
    | /tmp/xcpretty/bin/xcpretty -c
  
  buildresult=${PIPESTATUS[0]}

  echo —————— Completed tests for $platform.

  sleep 5  # Workaround for Travis log truncation

  exit $buildresult
